### ISSUE TITLE
Upstream sys crate fixes

### ISSUE THREAD

**Issue by kornelski** [zmwangx/rust-ffmpeg-sys#4]
I've revived meh's crate:

https://github.com/meh/rust-ffmpeg-sys

it now contains some fixes that aren't in this fork. I recommend cherry-picking them, or rebasing on the newer branch.

**Comment by zmwangx** [comment]
Thanks for the heads up, I cherry-picked most fixes. Two problems:

- I don't understand https://github.com/meh/rust-ffmpeg-sys/commit/6ee9c566dca93fe0738636e7aa073205f0589f79.

  - Why do you need to link to `libc++`/`libstdc++`?
  - The `pkg_config` crate already takes care of printing `cargo:rustc-link-search`, `cargo:rustc-link-lib`, etc., so not sure why there's custom code to print those again.

- https://github.com/meh/rust-ffmpeg-sys/pull/70 just isn't right... I rewrote the thing in d5b361d.

**Comment by kornelski** [comment]
Apple has deprecated and broken `libstdc++` in their clang, and `libc++` must be used instead. However, pkg-config still emits link instructions for `libstdc++`, which breaks builds on macOS.

**Comment by kornelski** [comment]
I've cherry-picked your libdrm change.

**Comment by zmwangx** [comment]
I know the `libc++`/`libstdc++` situation on macOS, I didn't realize `libavcodec` and `libavfilter` links to the C++ runtime in `Libs.private` though. I hardly ever bother with static linking on macOS so this slipped my mind.

The fix is very far from ideal though. This should definitely be fixed upstream. The easiest "fix" might be patching `libavcodec.pc` and `libavfilter.pc` directly, which can be done from the Homebrew formula for instance (but as a former Homebrew maintainer I can safely say this isn't a patch Homebrew would accept).

Btw, even with the patch `--features static` doesn't work for me on macOS — it fails during the linking stage with tons of undefined symbols, and I care too little about static linking to track them down...
